# Generated by Django 3.1 on 2020-08-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userinfo',
            new_name='Info',
        ),
    ]
