# Generated by Django 3.1 on 2020-08-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2app', '0002_auto_20200815_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Sid',
        ),
    ]
